Repository uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_009, pull requests merged in 2024-11, with the labels that each got.

#45 stable basic app version
  .gitignore
  app/controllers/application_controller.rb
  app/views/layouts/application.html.haml
  config/database.yml
  config/routes.rb
Labels: story, dependencies

#50 Heroku Deployment for Madhus Signup Page Code
  config/credentials.yml.enc
  public/assets/.sprockets-manifest-e4b19f8faea6272c885223d4bcb5cd05.json
  public/assets/application-4a3552b9c52d774646f7040e0aad806934e656609fe8b9dc4f0b33b27e0222ab.css
  public/assets/application-4a3552b9c52d774646f7040e0aad806934e656609fe8b9dc4f0b33b27e0222ab.css.gz
  public/assets/custom-271d95f408d5174a5afbaaf4f1c854a7d71bd8b52a44e989bfdc2ad854c5a409.css
  public/assets/custom-271d95f408d5174a5afbaaf4f1c854a7d71bd8b52a44e989bfdc2ad854c5a409.css.gz
Labels: pull request

#52 Pull Request: Integrate Bootstrap for Responsive and Modern UI Design #51
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/javascript/application.js
  app/views/layouts/application.html.haml
  config/importmap.rb
  config/initializers/assets.rb
Labels: pull request

#55 Pull Request: Navbar does not display the options as intended. #54
  app/views/layouts/application.html.haml
Labels: pull request

#63 PR: modified the routes, modified users and server models, Profile links created
  app/controllers/profiles_controller.rb
  app/controllers/servers_controller.rb
  app/models/user.rb
  app/views/profiles/edit.html.haml
  app/views/profiles/show.html.haml
  app/views/servers/edit.html.haml
  app/views/servers/index.html.haml
  app/views/servers/new.html.haml
  app/views/servers/show.html.haml
  config/routes.rb
  db/migrate/20241114074811_devise_create_users.rb
  db/migrate/20241114074812_create_wallets.rb
  db/migrate/20241114074813_create_transactions.rb
  db/migrate/20241114074815_create_items.rb
  db/migrate/20241114074816_create_inventories.rb
  db/migrate/20241114074819_create_server_users.rb
  db/migrate/20241114074820_create_grid_cells.rb
  db/migrate/20241114074821_create_contents.rb
  db/migrate/20241114074823_create_treasures.rb
  db/migrate/20241114074824_create_treasure_finds.rb
  db/migrate/20241114074825_create_scores.rb
  db/migrate/20241114074826_create_leaderboards.rb
  db/migrate/20241114074828_create_leaderboard_entries.rb
  db/migrate/20241114092858_add_username_to_users.rb
  db/migrate/20241115210949_add_recoverable_to_users.rb
  db/migrate/20241118015437_create_servers.rb
  db/migrate/20241118015525_create_users.rb
  db/migrate/20241118015625_add_devise_to_users.rb
  db/schema.rb
  public/assets/.sprockets-manifest-e4b19f8faea6272c885223d4bcb5cd05.json
  public/assets/application-f8eca2a5d1c0828dfeaceb619e1b43758da34eaee27b44a53bf4ae16eb1d53e7.css
  public/assets/application-f8eca2a5d1c0828dfeaceb619e1b43758da34eaee27b44a53bf4ae16eb1d53e7.css.gz
  public/assets/trix-ada334d1ee170a1585db0d298cb4e4380191d926f8de31e82ce44a3d1544ad13.css
  public/assets/trix-ada334d1ee170a1585db0d298cb4e4380191d926f8de31e82ce44a3d1544ad13.css.gz
Labels: pull request

#64 Avinash
  app/assets/images/default_background.png
  app/assets/images/game_background.png
  app/assets/images/start_background.png
  app/assets/stylesheets/application.scss
  app/views/layouts/application.html.haml
  app/views/profiles/show.html.haml
Labels: enhancement, pull request

#65 heroku push avinash profile link updates code
  config/application.rb
  config/environments/production.rb
  public/assets/.sprockets-manifest-e4b19f8faea6272c885223d4bcb5cd05.json
  public/assets/application-8904d95d1879432a071ea129e916e9cf8d2c32077f940b7d9d2dbbdeea6ac5e7.css
  public/assets/application-8904d95d1879432a071ea129e916e9cf8d2c32077f940b7d9d2dbbdeea6ac5e7.css.gz
  public/assets/default_background-57980f29fa1caa056e848a2296bc047a9491d9b9748385dc7f3e03521150206c.png
  public/assets/game_background-a4a1aeccc3ff4d4243638f214334ff271c8202088c92f2594af475e71cd14571.png
  public/assets/start_background-ac8a961886bc3b756ec2b3ecd4e2cdd8e79630550dc4453f1bc336eaf98c8c68.png
  static.json
Labels: bug

#78 updating the migrations
  db/migrate/20241122020613_create_contents.rb
  db/migrate/20241122020619_create_grid_cells.rb
  db/migrate/20241122020625_create_inventories.rb
  db/migrate/20241122020632_create_items.rb
  db/migrate/20241122020638_create_leaderboard_entries.rb
  db/migrate/20241122020644_create_leaderboards.rb
  db/migrate/20241122020651_create_scores.rb
  db/migrate/20241122020702_create_server_users.rb
  db/migrate/20241122020711_create_transactions.rb
  db/migrate/20241122020718_create_treasure_finds.rb
  db/migrate/20241122020723_create_treasures.rb
  db/migrate/20241122020733_create_wallets.rb
  db/migrate/20241122020745_add_foreign_keys_to_grid_cells.rb
  db/migrate/20241122020746_add_foreign_keys_to_inventories.rb
  db/migrate/20241122020748_add_foreign_keys_to_leaderboard_entries.rb
  db/migrate/20241122020749_add_foreign_keys_to_leaderboards.rb
  db/migrate/20241122020751_add_foreign_keys_to_scores.rb
  db/migrate/20241122020752_add_foreign_keys_to_server_users.rb
  db/migrate/20241122020753_add_foreign_keys_to_transactions.rb
  db/migrate/20241122020755_add_foreign_keys_to_treasure_finds.rb
  db/migrate/20241122020756_add_foreign_keys_to_treasures.rb
  db/migrate/20241122020758_add_foreign_keys_to_wallets.rb
  db/migrate_backup/20241118015437_create_servers.rb
  db/migrate_backup/20241118015525_create_users.rb
  db/migrate_backup/20241118015625_add_devise_to_users.rb
  db/schema.rb
  db/schema_backup.rb
  spec/rails_helper.rb
Labels: pull request

#84 Pull Request: Dynamic page title for each page
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/static_pages_controller.rb
  app/helpers/application_helper.rb
  app/helpers/static_pages_helper.rb
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/layouts/_flash.html.haml
  app/views/layouts/_footer.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
  app/views/profiles/edit.html.haml
  app/views/profiles/show.html.haml
  app/views/servers/edit.html.haml
  app/views/servers/index.html.haml
  app/views/servers/new.html.haml
  app/views/servers/show.html.haml
  app/views/static_pages/about.html.haml
  app/views/static_pages/home.html.haml
  config/routes.rb
  spec/helpers/static_pages_helper_spec.rb
  spec/requests/static_pages_spec.rb
  spec/views/static_pages/about.html.haml_spec.rb
  spec/views/static_pages/home.html.haml_spec.rb
Labels: pull request
